spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?serverTimezone=GMT
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.ts.tokentest.entity

